### ISSUE TITLE
Fix all endpoints with defined request and response structure

### ISSUE THREAD

**Issue by ankit-dc** [dat-labs/dat-api#2]

**Comment by ankit-dc** [comment]
Working on this issue: Here's the link: [Link](https://github.com/ankit-dc/dat-api/tree/feature/fix-all-routes-with-proper-req-and-resp)

**Comment by dc-rahul** [comment]
Ankit.. please update the **pyproject.toml** file in **dat-api** to include **dat** dependencies from main repo now since everything is merged to main.. So things should look like this:
```
dat-core = {git = "ssh://git@github.com/dat-labs/dat-core"}
verified-sources = {git = "ssh://git@github.com/dat-labs/verified-sources"}
verified-generators = {git = "ssh://git@github.com/dat-labs/verified-generators"}
verified-destinations = {git = "ssh://git@github.com/dat-labs/verified-destinations"}
```

**Comment by riju-dc** [comment]
`destination/spec` is returning `Internal Server Error`
```bash
curl -X 'GET' \
  'http://localhost:8000/actors/pinecone-uuid/spec' \
  -H 'accept: application/json'
```
